name: refresh data

on:
  workflow_dispatch:
  schedule:
    - cron: "10 0 * * *"

jobs:
  refresh:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run updater
      run: |
        ./ci.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
